fluentbit_version: "2.1.7"

fluentbit_user: "fluentbit"
fluentbit_group: "fluentbit"
fluentbit_install_dir: "/opt/fluentbit"
fluentbit_config_dir: "/etc/fluentbit"

elasticsearch_host: "http://localhost:9200"
elasticsearch_index: "fluentbit-logs"

fluentbit_arch_map:
  x86_64: "amd64"
  aarch64: "arm64"

