node_exporter_version: "1.7.0"
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
node_exporter_install_dir: "/opt/node_exporter"
node_exporter_config_dir: "/etc/node_exporter"
node_exporter_port: 9100

