---
- name: Prometheus install
  hosts: promserver 
  become: yes  
  become_method: sudo
  tags:
    - monitoring
    - promserver  
  roles:
    - prometheus

- name: Instaling and configuring  Node Exporter
  hosts: node_exporters
  become: yes  
  become_method: sudo
  roles:
    - node_exporters  
  tags:
    - monitoring
    - node_exporter  


- name: Install and configure Elasticsearch and Kibana
  hosts: elastic_kibana 
  become: yes  
  become_method: sudo
  roles:
    - elastic_kibana
  tags:
    - monitoring
    - elastic_kibana

- name: Install Fluent Bit
  hosts: log_servers
  become: yes  
  become_method: sudo
  tags:
    - monitoring
    - logging  
  roles:
    - fluentbit

