- name: Reload Node Exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes

- name: Reload Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes
  delegate_to: "{{ groups['prometheus'][0] }}"

