prometheus_version: "3.2.0"
prometheus_user: "prometheus"
prometheus_group: "prometheus"
prometheus_install_dir: "/opt/prometheus"
prometheus_config_dir: "/etc/prometheus"
prometheus_data_dir: "/var/lib/prometheus"
prometheus_port: 9090

