- name: Create group prometheus "{{ prometheus_group }}"
  ansible.builtin.group:
    name: "{{ prometheus_group }}"
    state: present

- name: Create user prometheus "{{ prometheus_user }}"
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    shell: /usr/sbin/nologin
    createhome: no

- name: Create folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0755"
  loop:
    - "{{ prometheus_install_dir }}"
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Download and install  Prometheus
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-arm64.tar.gz"
    dest: "{{ prometheus_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- name: Set systemd unit-file
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: "0644"
  notify: Restart Prometheus

- name: Install Prometheus config yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0644"
  notify: Reload Prometheus

- name: Run and enable Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes
    state: started
    daemon_reload: yes

