- name: Create Fluent Bit group
  ansible.builtin.group:
    name: "{{ fluentbit_group }}"
    system: yes

- name: Create Fluent Bit user
  ansible.builtin.user:
    name: "{{ fluentbit_user }}"
    group: "{{ fluentbit_group }}"
    system: yes
    create_home: no

#------------Install Fluentbit----------------------------------
- name: Add Fluent Bit GPG Key
  ansible.builtin.apt_key:
    url: https://packages.fluentbit.io/fluentbit.key
    state: present

- name: Add Fluent Bit Repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.fluentbit.io/ubuntu/jammy jammy main"
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Fluent Bit
  ansible.builtin.apt:
    name: fluent-bit
    state: latest      
     
#------------------------------------------------------------------------

- name: Create Fluent Bit config directory
  ansible.builtin.file:
    path: "{{ fluentbit_config_dir }}"
    state: directory
    owner: "{{ fluentbit_user }}"
    group: "{{ fluentbit_group }}"
    mode: "0755"

- name: Deploy Fluent Bit configuration
  ansible.builtin.template:
    src: "fluentbit.conf.j2"
    dest: "{{ fluentbit_config_dir }}/fluent-bit.conf"
    owner: "{{ fluentbit_user }}"
    group: "{{ fluentbit_group }}"
    mode: "0644"
  notify: Restart Fluent Bit


- name: Enable and start Fluent Bit service
  ansible.builtin.systemd:
    name: fluent-bit
    enabled: yes
    state: started
    daemon_reload: yes

